### PR TITLE
Initial support for Microsoft.Data.Sqlite

### PR DESCRIPTION
**Pull request by rhegner**
see issue #359

### CODE REVIEW

**Comment by schotime** [comment]
Looks ok. Were you able to run the full test suite against it?

**Comment by rhegner** [comment]
I haven't tried to run the test suite yet. But I will try that...

**Comment by rhegner** [comment]
I couldn't get the tests to run..... I compiled the whole solution but I didn't find a way to run the tests...

**Comment by schotime** [comment]
The tests run as a console application. You just need to adjust the config.

**Comment by schotime** [comment]
howd u go with this?

**Comment by rhegner** [comment]
I'm very busy with getting out a first version of our product for market trial. We discarded SqLite support for this first version. I will look into this once I have some more resources available...

**Comment by sebaFlame** [comment]
```
--- "a/NPoco\\src\\NPoco\\MappingFactory.cs"
+++ "b/NPoco\\src\\NPoco\\MappingFactory.cs"
@@ -28,11 +28,13 @@ public MappingFactory(PocoData pocoData, DbDataReader dataReader)
         {
             _pocoData = pocoData;
             _rowMapper = RowMappers.Select(mapper => mapper()).First(x => x.ShouldMap(pocoData));
-            _rowMapper.Init(dataReader, pocoData);
         }
 
         public object Map(DbDataReader dataReader, object instance)
         {
+            //re-init mapper for every row https://github.com/aspnet/Microsoft.Data.Sqlite/issues/300
+            //null gets mapped to Int32, in a later row it receives Int64 (INTEGER) and can't convert
+            _rowMapper.Init(dataReader, _pocoData);
             return _rowMapper.Map(dataReader, new RowMapperContext()
             {
                 Instance = instance,
```
This patch should allow the tests to run (I haven't tried, because I haven't found the time yet to rewrite the SQL). I don't know how this would affect performance.

**Comment by fosterwork** [comment]
Any update on this?

**Comment by rhegner** [comment]
Actually I recently made an attempt to make the test suite work for my pull request. I expected that I only need to slightly modify the tests for the existing System.Data.Sqlite provider.
But I realized that the test suite is far from being usable with the existing System.Data.Sqlite either - looks like there is quite some work to be done for both System.Data.Sqlite and Microsoft.Data.Sqlite (regarding testing). I'll absolutely need Sqlite support in the longer term, so at some point I'll be forced to look into this in more detail. But I'm too busy with other stuff at the moment.

**Comment by fosterwork** [comment]
Updating to Microsoft.Data.Sqlite version 2.0.0 fixed the "The IsolationLevel 'ReadCommitted' is invalid." error for me.

**Comment by schotime** [comment]
This really needs to be rebased before review.

**Pull request closed without merging**
