### PR TITLE
LinQ Supported DateTime.Year 

### PR DESCRIPTION
**Pull request by toolgood**
This code was not tested on Npoco, but it was tested in my own code set.

### CODE REVIEW

**Comment by toolgood** [comment]
Not Support  .NET Standard 1.3

**Comment by schotime** [comment]
Why is .NET Standard 1.3 not supported?

**Comment by toolgood** [comment]
MemberInfo no ReflectedType property.
And, I don't know where to get it.

**Comment by toolgood** [comment]
You can use the DeclaringType property.

**Comment by toolgood** [comment]
You need to add PostgreSQL and Oracle corresponding SqlExpression class

**Comment by schotime** [comment]
Definitely can get the type. GetMemberInfoType() I believe. 

Will need tests added too.

**Comment by MakiseKurisu** [comment]
@toolgood are you still working on this PR? I also encountered the same issue. Hope this will be part of the 4.0 release.

**Comment by schotime** [comment]
@toolgood this needs to be rebased and only contain the changes for the PR. I've noticed lots of new line characters etc included.

**Comment by toolgood** [comment]
I have modified.

**Pull request closed without merging**
