### PR TITLE
Adds SQL Server command formatting for easy copy & paste

### PR DESCRIPTION
**Pull request by tbasallo**
I made the current formatting tests use mySQL as a DB type to cover the other database types and I added a new set of tests with two database types (in the same file).  One for SqlServerDatabaseType and the other for the SqlServerDatabase. While they're the same under the covers, this ways it's covered in case a changes comes along later.

I made a few private members internal, to get access to them. Not sure if you prefer a different way.

Lastly, I added a new override method GetParameterPrefix() with no connectionstring parameter. There was a couple ways to do this and I went with the easiest for now. They both just return "@" with no logic.

### CODE REVIEW

**Comment by tbasallo** [comment]
For #429

**Comment by schotime** [comment]
This needs to be rebased if you don't mind @tbasallo. Sorry

**Comment by tbasallo** [comment]
@schotime I think I got this right. I am not all that great with the Git-ness.

Let me know if I need to change anything.

**Comment by schotime** [comment]
I had to manually merge, cause the rebase wasn't quite correct, but its in. thanks

**Comment by tbasallo** [comment]
I had a feeling something wasn't right. I kid you not, I must have been at it for like an hour. I read 4 tutorials and still...thanks for getting it in.

**Pull request closed without merging**
